name: remote_com_env
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - mlflow>=1.2.0
  - pandas>=1.2.3
  - pillow>=8.1.2
  - pip>=21.0.1
  - python>=3.9.2
  - scikit-learn>=0.24.1
  - scipy>=1.6.1
  - torchvision=0.11.1=py39_cu102
  - tqdm>=4.59.0
  - yaml>=0.2.5
  - jupyter>=1.0.0
  - seaborn>=0.10.1
  - xgboost>=4.10.3
  - pip:
    - matplotlib>=3.4.0
    - scikit-image>=0.18.1
    - statsmodels>=0.13.2
